version: '2'
services:
    # backup-config:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.config
    backup:
        build: .
        volumes:
            - ./docker/image_setup/docker-backup-entrypoint.sh:/docker-backup-entrypoint.sh:ro
            - ./app:/docker-backup-app:ro
            # - ./app/config.yml.dist:/etc/docker-backup/docker-backup.yml:ro
            - ./app/config.yml:/etc/docker-backup/docker-backup.yml:ro
            - ./docker/image_setup/etc/cron.d/docker-backup:/etc/cron.d/docker-backup:ro
            - ./docker-restore:/docker-restore
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - CONFIG_DESTINATIONS_LOCAL_FTP_PASSWORD=test_password
            - CONFIG_DESTINATIONS_C14_PRIVATE_TOKEN=private_token
            - CONFIG_SOURCES_TEST_MYSQL_USERNAME=mysql_user
            - CONFIG_SOURCES_TEST_MYSQL_PASSWORD=mysql_pass
        # command: force
        # command: worker test-fs
        # command: restore test-mysql
        # command: restore test-fs test-mysql
        command: debug
        networks:
            - ftp
        # volumes_from:
        #     - backup-config
    test_mysql:
        image: mysql:latest
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=true
            - MYSQL_USER=mysql_user
            - MYSQL_PASSWORD=mysql_pass
            - MYSQL_DATABASE=test_database
    test_data_cnf:
        image: busybox:latest
        command: sh /random.sh
        volumes:
            - ./docker/test_data/random.sh:/random.sh
            - /data
    test_data_env:
        image: busybox:latest
        command: sh /random.sh
        volumes:
            - ./docker/test_data/random.sh:/random.sh
            - /data
        environment:
          - DB_DESTINATION=local-ftp
          # - DB_DESTPATH=
          - DB_VOLUMES=/data
    ftp_server:
        image: akerbis/ftp:latest
        environment:
            - FTP_USER=test_user
            - FTP_PASS=test_pass
        ports:
            - "21:21"
            - "65000-65100:65000-65100"
        networks:
            - ftp
        volumes:
            - ./ftp-data:/data
networks:
    ftp:
        driver: bridge
